name: Go

on: push

jobs:

  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux', 'darwin']
        arch: ['amd64']
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install pkger
      run: go get github.com/markbates/pkger/cmd/pkger

    - name: Get dependencies
      run: go mod download

    - name: Generate
      run: go generate -v .

    - name: Build
      run: go build -v -ldflags='-w -s' .
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: installer-${{ matrix.os }}-${{ matrix.arch }}
        path: installer
